### PR TITLE
add content

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Review by ggoffy — COMMENTED** [review]
`* Table names should be singular, e.g. when we have a **User** entity class, the table in the database should be named ```user``` by default. See the reasoning behind it [here](https://tqdev.com/2021-should-table-names-be-singular-or-plural)`

I do not agree with this, because I see it always from perspective of database (content is:. multiple items) not from API perspective "DELETE item/23"

**Comment by mambax7** [comment]
Goffy, there will be always a discussion about plural or singular, but for me it's about consistency, simplicity,  convenience, and making my life easier. 
So if I have an entity object as "User" I don't have to think about what is the "plural" version of that name for a table, i.e. "users", but I'm calling it exactly the same name, i.e. "user". It's easier to remember and easier to implement, especially when dealing with words that change its form in plurals, e.g. "life" and "lives", "repository" and "repositories", "address" and "addresses". It also makes easier for non-English speaking people. 

Good discussion is [here](https://www.databasestar.com/database-table-naming-conventions/), pointing to the top rated answer on [Stackoverflow](https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names)

Few more articles:
* [Use singular nouns for database table names](https://www.teamten.com/lawrence/programming/use-singular-nouns-for-database-table-names.html)
* [Naming Conventions in Database Modeling](https://www.vertabelo.com/blog/naming-conventions-in-database-modeling/)

**Comment by mambax7** [comment]
Goffy, by the way, I was originally for plurals, but after reading more about it, I've changed my mind, as singulars offer more consistency and convenience.

**Comment by mambax7** [comment]
I'm curious about the view of @geekwright and @zyspec?

**Pull request merged**
